resources:
- repo: self
queue:
  name: Hosted VS2017

steps:
- checkout: self
  persistCredentials: true
- script: |
    git config user.email "tim.forkmann@danpower.de"
    git config user.name "tforkmann"
- script: dotnet tool restore
  displayName: Tool restore
- script: dotnet fake build -t Build
  displayName: Run Build
