resources:
- repo: self
queue:
  name: Hosted VS2017

steps:
- task: DotNetCoreInstaller@0
  displayName: 'Use .NET Core sdk 5.0.100'
  inputs:
    version: 5.0.100
    includePreviewVersions: true
- checkout: self
  persistCredentials: true
- script: |
    git config user.email "tim.forkmann@danpower.de"
    git config user.name "tforkmann"
- script: dotnet tool restore
  displayName: Tool restore
- script: dotnet fake build -t RunTests
  displayName: Run RunTests
